[tool.black]
line-length = 88
target-version = ['py313']
skip-string-normalization = true

[tool.pyright]
typeCheckingMode = "basic"
stubPath = "stubs"

[tool.pytest.ini_options]
addopts = "--disable-warnings --ignore=tagi_test.py"
